### ISSUE TITLE
Appears to not support un-transpiled arrow functions

### ISSUE THREAD

**Issue by morewry** [opentable/spur-ioc#31]
When attempting to use an ES6 arrow function `() => { }` with spur-ioc injector in unit tests, got an error `TypeError: Cannot read property '1' of null at Util.parseDependencies (node_modules/spur-ioc/lib/Util.js:13:21)`.

The mocha unit tests running on Node.js 4.7.0 had the following:

```javascript
describe("TestSuite", () => {

  beforeEach(() => {
    injector().inject((TestDependency) => {
      this.TestDependency = TestDependency;
    });
  });

  it("should something", () => { });

});
```

When attempting to run the tests, the injector threw an error:

```
> mocha --reporter spec test/unit

  TestSuite
    1) "before each" hook for "should something"


  0 passing (147ms)
  1 failing

  1) TestSuite "before each" hook for "should something":
     TypeError: Cannot read property '1' of null
    at Util.parseDependencies (node_modules/spur-ioc/lib/Util.js:13:21)
    at Function.resolvableDependency (node_modules/spur-ioc/lib/Dependency.js:11:39)
    at Injector.addResolvableDependency (node_modules/spur-ioc/lib/ContainerManagement.js:18:52)
    at Injector.inject (node_modules/spur-ioc/lib/DependencyManagement.js:28:10)
    at Context.<anonymous> (test/unit/TestSuiteSpecs.js:4:16)

npm ERR! Test failed.  See above for more details.
```

The failure pointed to the line with a RegExp for a function declaration, so I tried updating to:

```javascript
describe("TestSuite", () => {

  beforeEach(() => {
    injector().inject(function (TestDependency) {
      this.TestDependency = TestDependency;
    }.bind(this));
  });

  it("should something", () => { });

});
```

After this, the error went away and tests ran:

```
> mocha --reporter spec test/unit

  TestSuite
    1) should something


  1 passing (167ms)
```

**Comment by morewry** [comment]
https://github.com/opentable/spur-ioc#usage-note-for-es6-syntax

**Comment by morewry** [comment]
Note that the second version below doesn't actually work as desired:

```javascript
beforeEach(() => {
    injector().inject(function (TestDependency) {
      this.TestDependency = TestDependency;
    }.bind(this));
});
```


This avoids the error related to the use of `() => { }`, but attempting to use the dependency results in,

```
Error: Resolver encountered errors
    at DependencyResolver.throwError (node_modules/spur-ioc/lib/DependencyResolver.js:182:11)
    at DependencyResolver.resolve (node_modules/spur-ioc/lib/DependencyResolver.js:191:12)
    at Function.resolve (node_modules/spur-ioc/lib/DependencyResolver.js:199:14)
    at Injector.resolveDependency (node_modules/spur-ioc/lib/DependencyManagement.js:5:57)
    at Injector.wrapper [as resolveDependency] (node_modules/lodash/lodash.js:4994:19)
    at Injector.inject (node_modules/spur-ioc/lib/DependencyManagement.js:29:17)
    at Context.<anonymous> (test/unit/CommandServiceSpecs.js:13:16)
```

In order to get this to work I had to do stuff like this, since I need access to `this`.

IIFE closure
```javascript
beforeEach(() => {
  injector().inject((function (instance) {
    return function (TestService) {
      instance.TestService = TestService;
    };
  })(this));
});
```

beforeEach closure
```javascript
beforeEach(() => {
  var _this = this;
  injector().inject(function (TestService) {
    _this.TestService = TestService;
  });
});
```

Bind
```javascript
beforeEach(() => {
  var injectionFn = function (TestService) {
    this.TestService = TestService;
  }.bind(this)
  injector().inject(function (TestService) {
    injectionFn(TestService);
  });
});
```

**Comment by ssetem** [comment]
if its any help I have this helper setup by  my globals in test runner
```javascript
global.injectIntoScope = (scope, deps)=> {
  let instances = injector().injectAndReturn(deps)
  _.assign(scope, instances)
}
```

then in test
```javascript

  beforeEach(function(){
    injectIntoScope(this, [
      "ContractCompiler"
    ])
  })
  it("ContractCompiler should exist", function(){
    expect(this.ContractCompiler).toBeTruthy()
  })
```

**Comment by ssetem** [comment]
I will also try to get es6 support PR soon

**Comment by morewry** [comment]
If you transpile your tests, the way spur-web does, you can use `() => { }` right now; it's only when you're running ES6 "natively", so I don't see it as urgent if the repetitiveness can be eliminated. Just good to have.
