### ISSUE TITLE
Utils.js/parseDependencies/rFunction: regex doesn't support arrow functions

### ISSUE THREAD

**Issue by wesww** [opentable/spur-ioc#37]
ref. https://github.com/opentable/spur-ioc/blob/master/src/Util.js#L5

Example:
```
injector().inject(function (example) {
  example.method();
}
```
The above code must be changed to the following to solve a breaking Error against our `prefer-arrow-callback` eslint rule:

```
injector().inject((example) => {
  example.method();
}
```
However, fixing this code _breaks_ spur ioc, because the ioc function regex doesn't support es2016 arrow functions.

```
node_modules/spur-ioc/lib/Util.js:13
    match(rfunction)[1].split(rcomma);
                    ^

TypeError: Cannot read property '1' of null
  at Util.parseDependencies (node_modules/GuestCenterCommonNode/node_modules/spur-ioc/lib/Util.js:13:21)
  at Function.resolvableDependency (node_modules/GuestCenterCommonNode/node_modules/spur-ioc/lib/Dependency.js:11:39)
  at Injector.addResolvableDependency (node_modules/GuestCenterCommonNode/node_modules/spur-ioc/lib/ContainerManagement.js:18:52)
  at Injector.inject (node_modules/GuestCenterCommonNode/node_modules/spur-ioc/lib/DependencyManagement.js:28:10)
  at Object.<anonymous> (server/src/start.js:3:12)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3
```

**Comment by acolchado** [comment]
@wesww We are aware of this [limitation #31](https://github.com/opentable/spur-ioc/issues/31), but at the moment we have not prioritized this considering there is a quick work around. 

We should chat as a group and see how this weighs against other priorities. I've asked a few other interested (the more passionate) parties to see if they are willing to work on the problem and submit an adjustment to support this. Same goes to you, but I will notify you as soon as we decide how we will prioritize this.

**Comment by ssetem** [comment]
Originally borrowed angular.js parser, they have updated to support arrow functions.

https://github.com/angular/angular.js/blob/master/src/auto/injector.js#L66-L126

perhaps we could copy over again :)

**Comment by acolchado** [comment]
Closed by https://github.com/opentable/spur-ioc/pull/53
