### ISSUE TITLE
Exception in Dependency: Improve error thrown by the container

### ISSUE THREAD

**Issue by acolchado** [opentable/spur-ioc#38]
Currently, when there is an exception in one of the dependencies we are missing out on some useful information. For example, the following message is thrown when an error is thrown in my a stub that I've setup inside of `DiscoveryManagerSpec.coffee:27:44`. With this error message I can not tell what it is that is broken:

```shell
ERROR Exception in Dependency ----- $$harness-discovery-test in  $$harness-discovery-test
ERROR 	at ~/Code/opentable/npm/harness/harness-discovery/test/unit/discovery/DiscoveryManagerSpec.coffee:27:44
	at Injector.resolveDependency (~/Code/opentable/npm/harness/harness-discovery/node_modules/spur-ioc/lib/DependencyManagement.js:5:57)
	at Injector.wrapper [as resolveDependency] (~/Code/opentable/npm/harness/harness-discovery/node_modules/spur-ioc/node_modules/lodash/lodash.js:4968:19)
	at Injector.inject (~/Code/opentable/npm/harness/harness-discovery/node_modules/spur-ioc/lib/DependencyManagement.js:29:17)
	at Context.<anonymous> (~/Code/opentable/npm/harness/harness-discovery/test/unit/discovery/DiscoveryManagerSpec.coffee:17:8)
	at callFn (~/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runnable.js:345:21)
	at Hook.Runnable.run (~/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runnable.js:337:7)
	at next (~/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:309:10)
	at Immediate.<anonymous> (~/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:339:5)
	at runCallback (timers.js:666:20)
	at tryOnImmediate (timers.js:639:5)
	at processImmediate [as _immediateCallback] (timers.js:611:5)
ERROR 	at ~/Code/opentable/npm/harness/harness-discovery/test/unit/discovery/DiscoveryManagerSpec.coffee:27:44
	at Injector.resolveDependency (~/Code/opentable/npm/harness/harness-discovery/node_modules/spur-ioc/lib/DependencyManagement.js:5:57)
	at Injector.wrapper [as resolveDependency] (~/Code/opentable/npm/harness/harness-discovery/node_modules/spur-ioc/node_modules/lodash/lodash.js:4968:19)
	at Injector.inject (~/Code/opentable/npm/harness/harness-discovery/node_modules/spur-ioc/lib/DependencyManagement.js:29:17)
	at Context.<anonymous> (~/Code/opentable/npm/harness/harness-discovery/test/unit/discovery/DiscoveryManagerSpec.coffee:17:8)
	at callFn (~/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runnable.js:345:21)
	at Hook.Runnable.run (~/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runnable.js:337:7)
	at next (~/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:309:10)
	at Immediate.<anonymous> (~/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:339:5)
	at runCallback (timers.js:666:20)
	at tryOnImmediate (timers.js:639:5)
	at processImmediate [as _immediateCallback] (timers.js:611:5)
```
When the error is thrown as we try to initialize the dependency, we run it through a [.cleanStack(error)](https://github.com/opentable/spur-ioc/blob/master/src/DependencyResolver.js#L148). This ends up removing useful details about the failure.

@ssetem I can't recall the reason we had to clean the stack, but I do recall that you mentioned that we should remove it. That we may not need it anymore.

Without the `cleanStack` call, we get a more descriptive error:

```shell
TypeError: sinon.stub(...).returnes is not a function
    at ~/Code/opentable/npm/harness/harness-discovery/test/unit/discovery/DiscoveryManagerSpec.coffee:27:44
    at DependencyResolver.resolveDependencies (~/Code/opentable/npm/harness/harness-discovery/node_modules/spur-ioc/lib/DependencyResolver.js:146:31)
    at DependencyResolver.wrapper [as resolveDependencies] (~/Code/opentable/npm/harness/harness-discovery/node_modules/spur-ioc/node_modules/lodash/lodash.js:4968:19)
    at DependencyResolver.resolve (~/Code/opentable/npm/harness/harness-discovery/node_modules/spur-ioc/lib/DependencyResolver.js:193:28)
    at Function.resolve (~/Code/opentable/npm/harness/harness-discovery/node_modules/spur-ioc/lib/DependencyResolver.js:205:14)
    at Injector.resolveDependency (~/Code/opentable/npm/harness/harness-discovery/node_modules/spur-ioc/lib/DependencyManagement.js:5:57)
    at Injector.wrapper [as resolveDependency] (~/Code/opentable/npm/harness/harness-discovery/node_modules/spur-ioc/node_modules/lodash/lodash.js:4968:19)
    at Injector.inject (~/Code/opentable/npm/harness/harness-discovery/node_modules/spur-ioc/lib/DependencyManagement.js:29:17)
    at Context.<anonymous> (~/Code/opentable/npm/harness/harness-discovery/test/unit/discovery/DiscoveryManagerSpec.coffee:17:8)
    at callFn (~/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runnable.js:345:21)
    at Hook.Runnable.run (~/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runnable.js:337:7)
    at next (~/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (~/.nvm/versions/node/v6.10.1/lib/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

Will be looking into this soon, but wanted to start a conversation to see if anyone had some suggestions. Please take a look a the library and make any suggestions if you got them. Examples of these issues would also be helpful for other items you would like to resolve. Please provide a repo or gist that reproduces the issue.

cc @KalevRK @aselbie @mdboop @denisos

**Comment by ssetem** [comment]
yep we should remove cleanStack, looks like its doing damage now

**Comment by acolchado** [comment]
@ssetem I was thinking the same thing. Just have not had a chance to look through it. It's actually hiding some errors.
